"""
opennote_service.py
────────────────────
Handles all OpenNote API calls for the Whisper app.

FIX: generate_lesson() now ALWAYS returns real lesson text, even when no
journal content exists. It calls FeatherlessService directly as a fallback
so the user always gets a spoken lesson.

OUTPUT (mobile-safe, no raw URLs ever):
  LessonContent:
    - text:             Full plain-text explanation (always present)
    - image_queries:    Populated by Featherless after this call
    - source_summaries: Populated by Featherless after this call
    - video_url:        Only set on explicit generate_video=True request
    - from_journal:     True if text came from user's own OpenNote journal

Install:
  pip install opennote python-dotenv
"""

import os
import time
import json
from typing import Optional, TYPE_CHECKING
from dotenv import load_dotenv
from opennote import OpennoteClient
from models import LessonContent

if TYPE_CHECKING:
    from featherless_service import FeatherlessService

load_dotenv()

DEBUG_RAW_RESPONSE = True
DEFAULT_MODEL = "picasso"


# ── Main Service ──────────────────────────────────────────────────────────────

class OpenNoteService:
    """
    Generates lesson content for any topic.

    Always returns a LessonContent with real lesson text — either from the
    user's OpenNote journals, or generated by Featherless as a fallback.

    Usage:
        featherless = FeatherlessService()
        opennote = OpenNoteService(featherless=featherless)
        lesson = opennote.generate_lesson("How does mitosis work?")
        print(lesson.text)  # always real lesson text
    """

    def __init__(self, api_key: str = None, featherless: "FeatherlessService" = None):
        """
        Args:
            api_key:      OpenNote API key (or set OPENNOTE_API_KEY in .env)
            featherless:  FeatherlessService instance used as text generation
                          fallback when no journal content is found.
                          If not provided, the fallback is disabled and a
                          placeholder is returned instead.
        """
        self.api_key = api_key or os.getenv("OPENNOTE_API_KEY")
        if not self.api_key:
            raise ValueError(
                "OpenNote API key not found. "
                "Set OPENNOTE_API_KEY in your .env file."
            )
        self.client = OpennoteClient(api_key=self.api_key)
        self.featherless = featherless  # Optional fallback for text generation

    # ── Primary Method ────────────────────────────────────────────────────────

    def generate_lesson(
        self,
        topic: str,
        journal_id: str = None,
        generate_video: bool = False,
        poll_interval: int = 5,
        timeout: int = 120,
    ) -> LessonContent:
        """
        Main entry point. Always returns a LessonContent with real lesson text.

        Content priority:
          1. Specific journal (if journal_id given)
          2. Best matching journal found by keyword search
          3. Featherless generates lesson text directly (fallback)
          4. Placeholder text (if Featherless not configured)

        Args:
            topic:          The topic or subtopic to explain
            journal_id:     Optional — pull from a specific user journal
            generate_video: ONLY pass True on explicit user request (slow + costs credits)
            poll_interval:  Seconds between video job status checks
            timeout:        Max seconds to wait for video job

        Returns:
            LessonContent with text always populated.
        """
        print(f"[OpenNote] Generating lesson: '{topic}'")
        lesson = LessonContent(topic=topic, text="")

        # ── Priority 1: specific journal ──────────────────────────────────────
        if journal_id:
            text = self._text_from_journal(journal_id, topic)
            if text:
                lesson.text = text
                lesson.from_journal = True
                print(f"[OpenNote] Using journal: {journal_id}")

        # ── Priority 2: search journals ───────────────────────────────────────
        if not lesson.text:
            text, matched = self._search_journals(topic)
            if text:
                lesson.text = text
                lesson.from_journal = True
                print(f"[OpenNote] Matched journal: '{matched}'")

        # ── Priority 3: Featherless generates lesson text ─────────────────────
        if not lesson.text:
            if self.featherless:
                print(f"[OpenNote] No journal found — asking Featherless to generate lesson...")
                lesson.text = self.featherless.generate_lesson_text(topic)
            else:
                # Featherless not configured — return a clear placeholder
                lesson.text = (
                    f"No lesson content found for '{topic}'. "
                    f"Please configure FeatherlessService or add a journal on this topic."
                )
                print(f"[OpenNote] WARNING: No Featherless configured, returning placeholder.")

        # ── Optional: video (explicit request only) ───────────────────────────
        if generate_video:
            print(f"[OpenNote] Video requested — starting job (30-120s)...")
            try:
                result = self._create_video(topic, poll_interval, timeout)
                lesson.video_url = result.get("url")
                # Use video script as lesson text if available — it's richer
                if result.get("text"):
                    lesson.text = result["text"]
                    print(f"[OpenNote] Using video script as lesson text")
            except Exception as e:
                print(f"[OpenNote] Video failed: {e} — continuing with text only")

        print(f"[OpenNote] Done — {lesson.summary()}")
        return lesson

    # ── Journal Methods ───────────────────────────────────────────────────────

    def list_journals(self) -> list:
        """
        Returns all journals in the user's account.
        Works with read-only API keys.
        """
        response = self.client.journals.list()
        if DEBUG_RAW_RESPONSE:
            self._debug_print("journals.list()", response)
        if not getattr(response, "success", False):
            print("[OpenNote] journals.list() returned success=False")
            return []
        return getattr(response, "journals", []) or []

    def _text_from_journal(self, journal_id: str, topic: str) -> str:
        """Fetches and returns trimmed plain text from a specific journal."""
        try:
            response = self.client.journals.content(journal_id)
            if DEBUG_RAW_RESPONSE:
                self._debug_print(f"journals.content({journal_id})", response)
            text = self._extract_text(response)
            return self._trim_to_topic(text, topic) if text else ""
        except Exception as e:
            print(f"[OpenNote] Failed to fetch journal {journal_id}: {e}")
            return ""

    def _search_journals(self, topic: str) -> tuple[str, str]:
        """
        Searches user journals for content relevant to the topic.
        Returns (text, journal_title) or ("", "") if nothing found.
        """
        try:
            journals = self.list_journals()
            if not journals:
                return "", ""
            keywords = [w.lower() for w in topic.split() if len(w) > 3]
            for journal in journals:
                title = str(getattr(journal, "title", "") or "").lower()
                if any(kw in title for kw in keywords):
                    journal_id = getattr(journal, "id", None)
                    if journal_id:
                        text = self._text_from_journal(journal_id, topic)
                        if text:
                            return text, title
        except Exception as e:
            print(f"[OpenNote] Journal search error: {e}")
        return "", ""

    # ── Video (optional) ──────────────────────────────────────────────────────

    def _create_video(self, topic: str, poll_interval: int, timeout: int) -> dict:
        """Creates an OpenNote video job and polls until complete."""
        video = self.client.video.create(
            model=DEFAULT_MODEL,
            messages=[{"role": "user", "content": topic}],
            include_sources=True,
            search_for=topic,
            source_count=3,
            upload_to_s3=True,
            title=f"Lesson: {topic[:50]}",
        )
        if DEBUG_RAW_RESPONSE:
            self._debug_print("video.create()", video)

        video_id = video.video_id
        elapsed = 0
        while elapsed < timeout:
            status = self.client.video.status(video_id)
            if DEBUG_RAW_RESPONSE and elapsed == 0:
                self._debug_print("video.status() first poll", status)

            job_status = getattr(status, "status", None)
            if job_status == "completed":
                url = next((getattr(status, f, None) for f in ["url", "video_url", "s3_url"]), None)
                text = next((getattr(status, f, None) for f in ["script", "transcript", "text", "content"]), None)
                return {"url": url, "text": text}
            elif job_status == "failed":
                raise RuntimeError(f"Video job failed: {status}")

            print(f"[OpenNote] Video: '{job_status}' — retrying in {poll_interval}s...")
            time.sleep(poll_interval)
            elapsed += poll_interval

        raise TimeoutError(f"Video timed out after {timeout}s")

    # ── Text Helpers ──────────────────────────────────────────────────────────

    def _trim_to_topic(self, text: str, topic: str, max_chars: int = 3000) -> str:
        """Trims long journal content to the most relevant section."""
        if len(text) <= max_chars:
            return text
        keywords = set(topic.lower().split())
        paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
        scored = sorted(
            [(len(keywords & set(p.lower().split())), p) for p in paragraphs],
            reverse=True
        )
        result, total = [], 0
        for _, para in scored:
            if total + len(para) > max_chars:
                break
            result.append(para)
            total += len(para)
        return "\n\n".join(result) if result else text[:max_chars]

    def _extract_text(self, response) -> str:
        """Pulls plain text from a response object."""
        for f in ["content", "text", "body", "markdown", "data"]:
            value = getattr(response, f, None)
            if value and isinstance(value, str) and len(value.strip()) > 20:
                return value.strip()
        return ""

    # ── Debug ─────────────────────────────────────────────────────────────────

    def _debug_print(self, label: str, obj) -> None:
        print(f"\n{'─' * 55}")
        print(f"[OpenNote DEBUG] {label}")
        try:
            print(json.dumps(obj.__dict__, indent=2, default=str))
        except Exception:
            print(repr(obj))
        print(f"{'─' * 55}\n")

# ── Quick Test ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Usage: python opennote_service.py
    Requires OPENNOTE_API_KEY and FEATHERLESS_API_KEY in .env
    """
    # Import here to avoid circular import at module level
    from featherless_service import FeatherlessService

    featherless = FeatherlessService()
    service = OpenNoteService(featherless=featherless)

    print("=" * 55)
    print("TEST 1: Lesson — no journal (Featherless fallback)")
    print("=" * 55)
    lesson = service.generate_lesson("How does mitosis work?")
    print(f"\nSummary:      {lesson.summary()}")
    print(f"From journal: {lesson.from_journal}")
    print(f"\nLesson text:\n{lesson.text}")

    print("\n" + "=" * 55)
    print("TEST 2: List journals")
    print("=" * 55)
    journals = service.list_journals()
    print(f"Found {len(journals)} journal(s):")
    for j in journals:
        print(f"  - '{getattr(j, 'title', 'Untitled')}' (id: {getattr(j, 'id', '?')})")

    if journals:
        print("\n" + "=" * 55)
        print("TEST 3: Lesson — from first journal")
        print("=" * 55)
        first_id = getattr(journals[0], "id", None)
        topic = getattr(journals[0], "title", "this topic")
        if first_id:
            lesson = service.generate_lesson(topic, journal_id=first_id)
            print(f"\nSummary:      {lesson.summary()}")
            print(f"From journal: {lesson.from_journal}")
            print(f"\nLesson text preview:\n{lesson.text[:400]}...")

    print("\n" + "=" * 55)
    print("TEST 4: Video (costs credits — explicit request only)")
    print("=" * 55)
    if input("Generate video? (y/n): ").strip().lower() == "y":
        lesson = service.generate_lesson("How does mitosis work?", generate_video=True)
        print(f"Video URL: {lesson.video_url}")
    else:
        print("Skipped.")

    print("\n✓ Done.")